/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AgentDetailsPanel: typeof import('./src/components/analytics/AgentDetailsPanel.vue')['default']
    AnalyticsExportModal: typeof import('./src/components/analytics/AnalyticsExportModal.vue')['default']
    BarChart: typeof import('./src/components/charts/BarChart.vue')['default']
    CallAudioPlayer: typeof import('./src/components/calls/CallAudioPlayer.vue')['default']
    CallDetailsPanel: typeof import('./src/components/calls/CallDetailsPanel.vue')['default']
    ConversationFlowChart: typeof import('./src/components/analytics/ConversationFlowChart.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElResult: typeof import('element-plus/es')['ElResult']
    HeatmapChart: typeof import('./src/components/charts/HeatmapChart.vue')['default']
    HistogramChart: typeof import('./src/components/charts/HistogramChart.vue')['default']
    LineChart: typeof import('./src/components/charts/LineChart.vue')['default']
    PieChart: typeof import('./src/components/charts/PieChart.vue')['default']
    ReportExportService: typeof import('./src/components/analytics/ReportExportService.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchResultCard: typeof import('./src/components/search/SearchResultCard.vue')['default']
    SearchResultItem: typeof import('./src/components/search/SearchResultItem.vue')['default']
    VoiceSearchComponent: typeof import('./src/components/search/VoiceSearchComponent.vue')['default']
  }
}
