version: '3.8'

# Development overrides for docker-compose.yml
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development

  ml-service:
    build:
      context: ./ml-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./ml-service:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: python -m flask run --host=0.0.0.0 --port=5000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    ports:
      - "8080:5173"  # Vite default port